Abraham Tesfaye Aredo
Lidiya Anteneh Mekuria
Nohamin Yemane Kidane
Nathnael Tessema Dawit
Besufikad Melesse Abdo
Hikma Ibrahim Ahmed
Tsiyon Muluken Andualem
Ygeremu Sisay Abo
Samuel Fikadu Karu
Naol Berhanu Woyessa
Anwar Gashaw Yimam
Aschalew Mamo Bogale
Befekadu Berhanu Burju
Girum Muluken Assefa
Yosbeki Endalu Worku
Misgana Abera Asfaw
Abenezer Tamirat Jijawo
Ebba Waqshum Dhugasa
Tinsae Bahiru Bekele
Yostina Abera Gobie
Kaleb Dida Abera
Ebba Tamiru Muleta
Dereje Alemu Bogale
Kiya Bekele Bayisa
Mahider Feleke Bitew
Lemi Sheleme Fayera
Chaltu Firomsa Gudeta
Ababiya Bayessa Erena
Gennet Teresa Mogasa
Addisu Derrese Zewde
Joseph Tadesse Moltumo
Awoke Gebrie Atinafu
Kaleab Mekonnen Hailemariam
Hiba Khalid Mohammed
Lidet Admassu Alemu
Ananya Daniel Lakew
Blen Amsalu Gobaw
Abdiwak Muleta Ejeta
Gerawerk Moges Tadesse
Elshaday Alem Ghebretsadikan
Arsema Degu Addis
Mickeyas Andualem Dejenu
Anuwar Muktar Aman
Biruk Tilahun Tafa
Gelila Haile Gebreyohannes
Sebrina Semir Redman
Dawud Gena Gemechu
Natnael Ejigu Mengistu
Roba Fufa Gemeda
Hiwot Yirga Worku
Abinet Teshome Diress
Desalew Gashaye Getinet
Amdetibeb Workineh Tefera
Bishaw Tesema Niguse
Dibora Endris Belay
Leul Mekonen Beyene
Nahom Lulu Mulugeta
Samrawit Asfaw Kidane
Agegnehu Teshome Zerihun
Amir Essa Ahmed
Michael Yirdaw Mazengia
Mairegeab Abera Afro
Henok Yohannes Goshu
Biniyam Kibir Molla
Jiru Gutema Biftu
Dawit Petros Hailu
Loza Mihret Dananto
Hera Zeleke Yitayew
Fikremariyam Fentahun Maseresha
Yibeltal Semunigus Bolka
Keneni Asefa Merga
Terbinos Abebe Birbirsa
Zikra Abdusemed Awol
Gadisa Adamu Mitiku
Kidus Seyoum Kebede
Amanuel Wabi Zewdie
Nigusie Bekele Aduna
Samuel Girma Gizaw
Firaol Dugassa Likassa
Haylie Adugna Yitayih
Elshaday Esayas Dejene
Saron Eshetu Mesele
Yisak Desalgn Kahsay
Abrham Asrat Sete
Abel Mekuriya Sergota
Eyuel Getachew Negash
Dagmawi Bekele Feyisa
Fenet Genene Girma
Kidus Kefyalew Sahle
Surafel Simachew Andarge
Habtamu Mesele Sorsa
Dagmawi Teklemarkos Abebe
Daniel Kumela Teressa
Nimona Engida Abdisa
Amanuel Tedila Debas
Fayera Diriba Regasa
Nathan Wondim Tiru
Ynebeb Dagne Mekonen
Akawak Chala Tefera
Esayas Olansa Kumela
Nafiyad Tola Zewude
Yonas Abrham Mulugata
Seyfadin Abdela Kedir
Phawulos Getachew Tiki
Selahadin Mohammed Hussein
Abel Adamu Worku
Samuel Gosaye Gugsa
Firew Wondimu Wotango
Fikir Ashenafi Getahun
Naol Chala Olana
Kaleab Telayneh Muche
Getinet Eshetu Habte
Hiwot Daniel Alemu
Amanuel Wondwossen Zewdie
Yoseph Tewolde Kibrom
Yeabsira Simeka Maru
Ermiyas Abera Tadeg
Bezawit Yosef Yigezu
Rekik Girma Tilahun
Yohannes Birhanu Wubie
Yared Atrsaw Andargei
Dibora Wondewosen Tsegaye
Mahlet Teklu Gebremedhin
Beemnet Tesfaye Haddis
Kenawak Ibsa Aboma
Amar Asfaw Dilala
Abubeker Abe Gashu
Abenezer Alemayehu Lemma
Maassas Michael Tobias
Wendmagegn Tajura Labena
Basleal Anteneh Girma
Bereketab Haileeyesus Shanka
Tesfahun Kassahun Alemu
Osama Ibrahim Yesuf
Bemnet Adugnaw Beyene
Yodahe Chala Negewo
Henok Tilahun Abebe
Yosef Gebreyesus Hagos
Sophonias Amsale Wube
Gedion George Desalgne
Natnael Yohannes Gesiab
Abdi Geremew Gebeyehu
Haregewoin Worku Gezahegn
Daniel Endalkachew Bayu
Michael Mitiku Shifaw
Eden Kibret Kassie
Natnael Mohammed Yimam
Yomiyu Zeleke Tefera
Yeabsira Bekele Rorissa
Edlawit Siraw Abate
Hermela Haylay Tewelay
Bereket Hailu Yosef
Yonatan Yishak Yifat
Harod Geremew Desu
Latiko Mulugeta Aga 
Michael Ashenafi Ambaw
Nuhamin Arega Asie
Benyas Berhanu Wolde
Eyosiyas Eyasu Berhanu
Beki Damtew Gudure
Rahel Mesfin Zenebe
Bereket Aschalew Tadese
Sofonias Betiglu Bekalu
Biruk Molla Temesgen
Nahom Cheru Abebe
Semir Said Bedru
Abenezer Kassa Mikoro
Lidiya Bokona Beyie
Biruk Derbie Mekuriaw
Yohannes Tadiwos Woldemedhin
Abiy Hunegnaw Tilahun
Yohannes Solomon Kebede
Hanan Husen Abdu
AMANUEL SOLOMON GERMAYE
DAGIM YOHANNES BEYENE
HINSERMU GEBI DALE
MARIAMAWIT WONDEMANEH GEBRU
NAHOM AMSALU BEZU
BENJAMIN ZELALEM KIROS
CHRISTINA PAULOS ISAK
YOHANAN BINIAM MEKRU
YOHANNES SAMUEL ZELEKE
YOHANNES TESFAYE YOSPHE
YONAS BIRUK TEKLU
YOSEPH GETACHEW BEKELE
BONSA FIKADU
FAZI SHAFI
ABDULMEJID HUSSEIN
MOHMMED AWOL
MELLAL CHALA
SIYEFEN WAIHUN
NARDOS TESFAYE 
MILIKI TOLLOSA                                                                                                 TSION MULUNEH
ABDULWAHID ALI EBRAHIM
ABDELLA DAWUD HUSSEN
HAYAT TEMAM SHANFULE
SOFIYA AHMED BELAY
KIDIST ADANE ASSEFA
YEABSRA HAILEMARIAM BIRESSAW
ELHAM MOHAMMED ABRAR
NARDOS DEREJE TADESSE
CHAM OKELLO GNIGELLO
HEMEN ABEBR BURUKE
OUSMAN AWAY DAMTAW
HAMZA HARUN ALI
MUJAHID ALI FEDLELMOWLA
KIDANEMARIAM HAILU ZEGEYE
DAWIT NEGASI BRHANE
TSIGABU SEYOUM NEUGS
ROBEL ZERADAWIT TKUE